### ISSUE TITLE
prediction files for all CAFA2 participants?

### ISSUE THREAD

**Issue by jhcepas** [yuxjiang/CAFA2#1]
Hi there, 
where could I find all (or at least some) of the prediction files used in the CAFA2 genome biology paper?

**Comment by yuxjiang** [comment]
Hello Huerta-Cepas,
Thank you for your email, however, we made it clear to the authors before their submissions in CAFA2 that we won't release their predictions, so unfortunately, we can't do that. Sorry.

Best regards,

Yuxiang Jiang
PhD candidate, Computer Science
Indiana University Bloomington
