### ISSUE TITLE
get protein coverage when calculating fmax in partial mode

### ISSUE THREAD

**Issue by jhcepas** [yuxjiang/CAFA2#2]
Hi, I could not find in the documentation the way to calculate protein coverage ("C" value in the paper figures) when calculating fmax in partial mode. 
Any help would be really appreciated!

**Comment by yuxjiang** [comment]
Hello,
The "coverage" (C) is calculated as the ratio of positively predicted (for at least one term besides the root) benchmark proteins over the size of the entire benchmark. You can find the details in cafa_eval_seq_curve.m.

Cheers,

Yuxiang Jiang
PhD candidate, Computer Science
Indiana University Bloomington

**Comment by jhcepas** [comment]
thanks!
